name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
          nimble install -y --depsOnly
          # toml_serialization is a test suite dependency
          nimble install -y toml_serialization
          nimble test
